#ifndef ROBOT_CONFIG_H
#define ROBOT_CONFIG_H

#define LEFT_SIDE_PIN 8
#define RIGHT_SIDE_PIN 9
#define LEFT_SPEED_PIN 7
#define RIGHT_SPEED_PIN 12

#define ZERO_PACE 0
#define MAX_PACE 6000000
#define MIN_PACE 400
#define DEFAULT_B_VALUE 100

#define INCREMENTAL_ENCODER_LEFT_PIN 48
#define INCREMENTAL_ENCODER_RIGHT_PIN 49

#define K_INC 0.006761690963676
#define WIDTH 208.1

#define ERROR_MARGIN_ROT 0.06
#define ERROR_MARGIN_POS 6

#define P_ROTATION_ERROR_COEFFICIENT 300
#define I_ROTATION_ERROR_COEFFICIENT 100
#define D_ROTATION_ERROR_COEFFICIENT 0

#define P_POSITION_ERROR_COEFFICIENT 3.2
#define I_POSITION_ERROR_COEFFICIENT 12.5
#define D_POSITION_ERROR_COEFFICIENT 0

#define KI_ROT_SAT 0.05
#define KI_POS_SAT 0.05

#define LOGGING true

#define LASER_LEFT_PIN A0
#define LASER_MID_PIN A1
#define LASER_RIGHT_PIN A2

#endif